package com.camavilca.zelper.constant;

public interface Constantine {

    String SESSION_USUARIO = "SESSION_USUARIO_INTERVIEW";
    String ACCESS_TOKEN = "ACCESS_TOKEN";
    String NEWUSUARIO = "USUARIO REGISTRADO";
    String SUCCESSUSER = "INGRESO SATISFACTORIO";

    String CREATE = "NUEVO REGISTRO";
    String UPDATE = "REGISTRO ACTUALIZADO";
    String DELETE = "REGISTRO ELIMINADO";

    String NO_EXIST_DB = "LOS DATOS NO EXISTEN EN LA BASE DE DATOS";

    String FIELS_NO_COMPLET = "DEBE COMPLETAR LOS CAMPOS REQUERIDOS";
    String EXIST_USER = "LOS DATOS YA EXISTEN";

}
